# Generated by Django 6.0.3 on 2026-03-05 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'place',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Место действия привычки'),
                ),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время в которое выполняется привычка')),
                ('action', models.CharField(max_length=1000, verbose_name='Действие (описание привычки)')),
                ('is_pleasant', models.BooleanField(verbose_name='Признак приятной привычки')),
                (
                    'periodicity',
                    models.PositiveIntegerField(default=1, verbose_name='Периодичность выполнения привычки (в днях)'),
                ),
                (
                    'award',
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name='Вознаграждение за полезную привычку'
                    ),
                ),
                ('duration', models.PositiveIntegerField(verbose_name='Время на выполнение привычки')),
                ('is_publicity', models.BooleanField(verbose_name='Признак публичности')),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
                (
                    'related_pleasant_habit',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='habits.habit',
                        verbose_name='Связанная приятная привычка',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
